import Work1 from "../../assets/work-1.svg"
import Work2 from "../../assets/work-2.svg"
import Work3 from "../../assets/work-3.svg"
import Work4 from "../../assets/work-4.svg"
import Work5 from "../../assets/work-5.svg"
import Work6 from "../../assets/work-6.svg"

const Menu = [
    {id:1,
    image: Work1,
    title:"mise en page",
    category:"Web",
    link:"https://drive.google.com/drive/folders/1rU8c0VHsec_F6HR7oKPe8XZ2KQIFojw7?usp=drive_link"},
    {id:2,
    image: Work2,
    title:"Kollision",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1A_dWJQkn03O-1WSmD9nLA2RgMHVyxzFC?usp=share_link"},
    {id:3,
    image: Work3,
    title:"RPG Java",
    category:"Java",
    link:"https://drive.google.com/drive/folders/1bgA3PY1WfyHpjAfiCscIwI2j91CEmGuE?usp=share_link"},
    {id:4,
    image: Work1,
    title:"Post React",
    category:"Web",
    link:"https://drive.google.com/drive/folders/14QjpardpjTQLdV4p17P4oQVxZ6WLafDH?usp=drive_link"},
    {id:5,
    image: Work1,
    title:"Barre de recherche",
    category:"Web",
    link:"https://drive.google.com/drive/folders/145XA7HHRC57BrwFG5vOV7mfu-NvYvcOF?usp=drive_link"},
    {id:6,
    image: Work2,
    title:"Tic Tac Toe",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1Yc53fy9bq-GcQ-V5xfMopWMVn4pz94FX?usp=sharing"},
    {id:7,
    image: Work2,
    title:"Jeu de la vie",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1Yc53fy9bq-GcQ-V5xfMopWMVn4pz94FX?usp=sharing"},
    {id:8,
    image: Work2,
    title:"Pierre feuille ciseaux",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1Yc53fy9bq-GcQ-V5xfMopWMVn4pz94FX?usp=sharing"},
    {id:9,
    image: Work2,
    title:"Jeu de cartes bataille",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1A_dWJQkn03O-1WSmD9nLA2RgMHVyxzFC?usp=share_link"},
    {id:10,
    image: Work2,
    title:"Grille clic exemple",
    category:"Python",
    link:"https://drive.google.com/drive/folders/1Yc53fy9bq-GcQ-V5xfMopWMVn4pz94FX?usp=sharing"},
    {id:11,
    image: Work1,
    title:"Tableau de Bord - html",
    category:"web",
    link:"https://drive.google.com/drive/folders/1jDuXH5OJlOKac4qQURXbgUyEHwtVhmVr?usp=drive_link"},
    {id:12,
    image: Work1,
    title:"Simple Texte",
    category:"web",
    link:"https://drive.google.com/drive/folders/1N06YdY_FSwm9eEmUBWCQFaBY8IjRAZtp?usp=drive_link"}
];

export default Menu;