const Data = [
    {id:1,
    category:"education",
    icon:"icon-graduation",
    year: "2023 - maintenant",
    title:"BTS SIO Option SLAM",
    desc:"H3 Hitema - Issy les moulineaux"},
    {id:2,
    category:"education",
    icon:"icon-graduation",
    year: "2022 - 2023",
    title:"Licence Histoire",
    desc:"Université Paris Est Créteil - Créteil"},
    {id:3,
    category:"education",
    icon:"icon-graduation",
    year: "2021 - 2022",
    title:"Double licence Mathématiques et informatiques ",
    desc:"Université Gustave eiffel  - Champs-sur-marne"},
    {id:4,
    category:"education",
    icon:"icon-graduation",
    year: "2018 - 2021",
    title:"Bacalauréat Mathématiques et Numériques et sciences de l’informatiques",
    desc:"Lycée René Descartes - Champs-sur-marne"},
    {id:5,
    category:"education",
    icon:"icon-graduation",
    year: "2014 - 2018",
    title:"Diplome nationale du Brevet",
    desc:"Collège Jean Wiener - Champs-sur-marne "},
    {id:6,
    category:"experience",
    icon:"icon-briefcase",
    year: "2023 - 2023",
    title:"Equipier polyvalent",
    desc:"Mac Donalds - Champs -sur - marne"},
    {id:7,
    category:"experience",
    icon:"icon-briefcase",
    year: "2018 - 2018",
    title:"Stagiaire en restauration",
    desc:"Tablapizza - Noisiel"}
];

export default Data;